# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5254bdeed162de33a3bd766a5dd5c292b1da747d3e51a28fd0f887ac855be81314466e653c2c424c99c7fb6c52ccb81a09b3c38659257f93ec2f072b6ac48c4e

test:
  secret_key_base: 0d723b3d64a7a9ef7642dea5a0240bc063fc47bfce6359a085c1dafcf2baf7aafcad433e8b8449b3d5493dc84c9e9eaa87f5c712b934c725896f990781a676c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
